export const SET_QUERY = 'SET_QUERY'
export const CLEAR_QUERY = 'CLEAR_QUERY'

export const START_AUTH = 'START_AUTH'
export const LOGIN_AUTH_USER = 'LOGIN_AUTH_USER'
export const LOGOUT_AUTH_USER = 'LOGOUT_AUTH_USER'

export const SET_ERROR = 'SET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'